TopLearn.Web/Areas/UserPanel/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TopLearn.Core.Services.Interfaces;

namespace TopLearn.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    [Authorize]
    public class HomeController : Controller
    {
        private IUserPanelService _panelService;

        public HomeController(IUserPanelService panelService)
        {
            _panelService = panelService;
        }

        public IActionResult Index()
        {
            return View(_panelService.GetUserInformation(User.Identity.Name));
        }
    }
}

TopLearn.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TopLearn.Core.DTOs;
using TopLearn.Core.Services.Interfaces;

namespace TopLearn.Web.Controllers
{
    public class HomeController : Controller
    {
        private IUserPanelService _panelService;
        private IUserService _userService;
        private ICourseService _courseService;
        public HomeController(IUserPanelService panelService, IUserService userService, ICourseService courseService)
        {
            _panelService = panelService;
            _userService = userService;
            _courseService = courseService;
        }
        public IActionResult Index()
        {
            ViewBag.PopularCourse = _courseService.GetPopularCourse();

            return View(_courseService.ShowCourse());
        }


        [Route("UserPanel/EditProfile")]
        [Authorize]
        public IActionResult EditProfile()
        {
            return View(_panelService.GetDataForUserProfileEdit(User.Identity.Name));
        }

        [HttpPost]
        [Route("UserPanel/EditProfile")]
        public IActionResult EditProfile(EditProfileViewModel edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }

            _panelService.EditProfile(User.Identity.Name, edit);

            //Logout User 
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return Redirect("/Login?EditProfile=true");
        }

        [Route("UserPanel/ChangePassword")]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [Route("UserPanel/ChangePassword")]
        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel change)
        {
            string CurrentUserName = User.Identity.Name;
            if (!ModelState.IsValid)
            {
                return View(change);
            }

            if (!_panelService.CompareOldPassword(CurrentUserName, change.OldPassword))
            {
                ModelState.AddModelError("OldPassword", errorMessage: "کلمه عبور فعلی صحیح نمی باشد");
                return View(change);
            }

            _panelService.ChangeUserPassword(CurrentUserName, change.Password);
            ViewBag.IsSuccess = true;
            return View();
        }


        [Route("OnlinePayment/{id}")]
        // int id ==> WalletId
        public IActionResult OnlinePayment(int id)
        {
            if (HttpContext.Request.Query["Status"] != ""
                && HttpContext.Request.Query["Status"].ToString().ToLower() == "ok"
                && HttpContext.Request.Query["Authority"] != ""
                )
            {

                string Authority = HttpContext.Request.Query["Authority"];

                var Wallet = _userService.GetWalletByWalletId(id);

                var Payment = new ZarinpalSandbox.Payment(Wallet.Amount);
                var Response = Payment.Verification(Authority).Result;

                if (Response.Status == 100)
                {
                    ViewBag.Code = Response.RefId;
                    ViewBag.IsSuccess = true;
                    Wallet.IsPayed = true;
                    _userService.UpdateWallet(Wallet);
                }
            }
            return View();
        }

        public IActionResult Error404()
        {
            return View();
        }
    }
}

TopLearn.Web/ViewComponents/LatestCoursesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using TopLearn.Core.Services.Interfaces;

namespace TopLearn.Web.ViewComponents
{
    public class LatestCoursesViewComponent : ViewComponent
    {
        private ICourseService _courseService;

        public LatestCoursesViewComponent(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("/Views/Shared/Components/LatestCoursesComponent/LatestCourses.cshtml", _courseService.ShowCourse()));
        }
    }
}

TopLearn.Web/Views/Home/ChangePassword.cshtml
@model TopLearn.Core.DTOs.ChangePasswordViewModel
@{
    ViewData["Title"] = "تغییر رمز عبور";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">تاپ لرن</a></li>
            <li class="breadcrumb-item active" aria-current="page"> تغییر رمز عبور </li>
        </ul>
    </nav>
</div>

<main>
    <div class="container">
        <div class="user-account">
            <div class="row">
                <partial name="_SideBar" />
                <div class="col-md-9 col-sm-8 col-xs-12">
                    @if (ViewBag.IsSuccess != null)
                    {
                        <div class="alert alert-success">
                            <p class="help-block"> رمز عبور شما با موفقیت تغییر کرد. </p>
                        </div>

                        <script src="js/Login.js"></script>
                    }
                    <section class="user-account-content">
                        <header>
                            <h1> تغییر رمز عبور </h1>
                        </header>
                        <div class="inner form-layer">
                            <form asp-action="ChangePassword" method="post">
                                <div class="row">
                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="username"><i class="zmdi zmdi-lock"></i></span>
                                            <input asp-for="OldPassword" type="text" class="form-control" placeholder="رمز عبور فعلی" aria-describedby="username">
                                        </div>
                                        <span asp-validation-for="OldPassword" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="username"><i class="zmdi zmdi-lock"></i></span>
                                            <input asp-for="Password" type="text" class="form-control" placeholder="رمز عبور جدید" aria-describedby="username">
                                        </div>
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="username"><i class="zmdi zmdi-lock"></i></span>
                                            <input asp-for="RePassword" type="text" class="form-control" placeholder="تکرار رمز عبور جدید" aria-describedby="username">
                                        </div>
                                        <span asp-validation-for="RePassword" class="text-danger"></span>
                                    </div>

                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <input type="submit" class="btn btn-success" value=" ذخیره تغییرات "/>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>

TopLearn.Web/Views/Home/EditProfile.cshtml
@model TopLearn.Core.DTOs.EditProfileViewModel
@{
    ViewData["Title"] = "ویرایش پروفایل";
}
<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">تاپ لرن</a></li>
            <li class="breadcrumb-item active" aria-current="page"> ویرایش پروفایل </li>
        </ul>
    </nav>
</div>

<main>
    <div class="container">
        <div class="user-account">
            <div class="row">
                <partial name="_UserPanelSideBar" />
                <div class="col-md-9 col-sm-8 col-xs-12">
                    <section class="user-account-content">
                        <header>
                            <h1> ویرایش حساب کاربری </h1></header>
                        <div class="inner form-layer">
                            <form asp-action="EditProfile" method="post" enctype="multipart/form-data">

                                <input type="hidden" asp-for="AvatarName"/>

                                <div class="row">
                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="username"><i class="zmdi zmdi-account"></i></span>
                                            <input asp-for="UserName" type="text" class="form-control" placeholder="نام کاربری" aria-describedby="username">
                                        </div>
                                    </div>
                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <span class="input-group-addon" id="email-address"><i class="zmdi zmdi-email"></i></span>
                                            <input asp-for="Email" type="email" class="form-control" placeholder="ایمیل" aria-describedby="email-address">
                                        </div>
                                    </div>

                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <div class="input-group">
                                            <p class="help-block">
                                                آواتار
                                            </p>
                                            <input type="file" class="form-control" asp-for="Avatar"/>
                                            <p class="text-info">لطفا فقط تصویر انتخاب کنید!</p>
                                            <br/>
                                            <img class="thumbnail" src="/UserAvatar/@Model.AvatarName" width="150" height="150"/>
                                        </div>
                                    </div>

                                    <div class="col-md-7 col-sm-8 col-xs-12">
                                        <button class="btn btn-success"> ویرایش اطلاعات </button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>

TopLearn.Web/Views/Home/Error404.cshtml
@{
    ViewData["Title"] = "Error404";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>صفحه ارور 404 گمشده در فضا :: دریافت شده از وب روبیک</title>
    <link type="text/css" href="/css/style2.css" rel="stylesheet" />
</head>
<body class="bg-purple">
    <div class="stars">
        <!-- start logo and menu -->
        <div class="custom-navbar">
            <div class="brand-logo">
                <img src="/pics/logo.svg" width="80px">
            </div>
            <div class="navbar-links">
                <ul>
                    <li><a href="#" target="_blank">صفحه نخست</a></li>
                    <li><a href="#" target="_blank">درباره ما</a></li>
                </ul>
            </div>
        </div>
        <!-- end logo and menu -->
        <!-- start content -->
        <div class="central-body">
            <img class="image-404" src="/pics/404.png" width="300px">
            <a href="/" class="btn-go-home" target="_blank">بازگشت</a>
        </div>
        <div class="objects">
            <img class="object_rocket" src="/pics/rocket.svg" width="40px">
            <div class="earth-moon">
                <img class="object_earth" src="/pics/earth.svg" width="100px">
                <img class="object_moon" src="/pics/moon.svg" width="80px">
            </div>
            <div class="box_astronaut">
                <img class="object_astronaut" src="/pics/astronaut.svg" width="140px">
            </div>
        </div>
        <div class="glowing_stars">
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
            <div class="star"></div>
        </div>
        <!-- end content -->
    </div>
    <script src="/js/jquery-3.1.1.min.js"></script>
</body><!-- This template has been downloaded from Webrubik.com -->
</html>

TopLearn.Web/Views/Home/Index.cshtml
@using TopLearn.Core.DTOs.Course
@using TopLearn.DataLayer.Entities.Course
@model Tuple<List<TopLearn.Core.DTOs.Course.ShowCourseListItemViewModel>,int>
@{
    ViewData["Title"] = "خانه";
    List<ShowCourseListItemViewModel> PopularCourse = ViewBag.PopularCourse as List<ShowCourseListItemViewModel>;
}

@section SearchBox {
    <header>
        <a href="" class="logo"><img src="images/logo.png"></a>
        <h1> با اساتید مجرب و کارآزموده در خودآموز تاپ لرن </h1>
        <h2> آموزش ببینید ، تجربه کسب کنید و بازار کار شوید </h2>
        <h3> با کمترین هزینه خودت یاد بگیر </h3>
    </header>
    <div class="search-form">
        <form action="/Course/FilterCourse" method="get">
            <input type="text" name="filter" id="autoFilter" placeholder="چی دوست داری یاد بگیری ؟">
            <button><i class="zmdi zmdi-search"></i></button>
        </form>
    </div>
}


<div class="container">
    <section class="terms-items">
        <header>
            <h2> آخرین دوره های تاپ لرن </h2>
            <a href=""> مشاهده همه دوره ها </a>
        </header>
        <div class="row">
            <!-- col -->
            <cache expires-after="@TimeSpan.FromMinutes(10)">
                @await Component.InvokeAsync("LatestCourses")
            </cache>
            <!-- /col -->
        </div>
    </section>

    <hr>

    <section class="terms-items">
        <header>
            <h2> دوره های محبوب تاپ لرن </h2>
            <a href=""> مشاهده همه دوره ها </a>
        </header>
        <div class="row">
            <!-- col -->
            @foreach (var course in PopularCourse)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 term-col">
                    <article>
                        <a href="/ShowCourse/@course.CourseId" class="img-layer"><img class="fixThumb" src="/CourseImages/Thumb/@course.ImageName"></a>
                        <h2><a href="/ShowCourse/@course.CourseId"> @course.CourseTitle </a></h2>
                        <span>
                            @((course.Price == 0) ? "رایگان" : course.Price.ToString("#,0"))
                        </span>
                        <i>@course.TotalTime</i>
                    </article>
                </div>
            }
            <!-- /col -->

        </div>
    </section>
</div>


@section Scripts {

    <script>
        $(document).ready(function () {
            $("#autoFilter").autocomplete({
                source: 'api/courseapi/search'
            });
        });
    </script>
}

TopLearn.Web/Views/Home/OnlinePayment.cshtml
@{
    ViewData["Title"] = "نتیجه پرداخت";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">تاپ لرن</a></li>
            <li class="breadcrumb-item active" aria-current="page"> نتیجه پرداخت </li>
        </ul>
    </nav>
</div>

<div class="container col-md-12 col-xs-12 col-sm-12 col-12 col-xl-12">
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success text-center">
            <h2> پرداخت با موفقیت انجام شد. </h2>
            <p>
                کد پیگیری : @ViewBag.Code
            </p>
        </div>
    }
    else
    {
        <div class="alert alert-danger text-center">
            <h2> پرداخت با موفقیت انجام نشد. </h2>
        </div>
    }
</div>
<br />
<br />
<br />